### ISSUE TITLE
Annoying alert

### ISSUE THREAD

**Issue by levipadre** [abjerner/Skybrud.Umbraco.Analytics#3]
Hi, thank you for the plugin.

However when I use multilange on the site and swith between the languages I always got this message in an alert says "MULTIPLE VARIANTS. FANCY!!!"

It's really annoying. Would you please remove it or handle somehow else?

Thanks!

**Comment by abjerner** [comment]
Hi @levipadre,

While not super informative, the alert is there as an error message. Variants are not fully supported, which is why you're seeing the error. I've pushed a new release so the content app is using `console.error` instead of `alert`.

https://github.com/abjerner/Skybrud.Umbraco.Analytics/releases/tag/v1.0.0-beta004

This does however not change that variants are still not fully supported. I think the package will just show statistics for the first (or default) culture, but I haven't really worked much on this part yet.

**Comment by levipadre** [comment]
Thank you! Can you release on nuget as well?

I'm watching the plugin if you make some changes with variants.

**Comment by abjerner** [comment]
It's already out on NuGet, but you have to include pre-releases when installing in Visual Studio:

https://www.nuget.org/packages/Skybrud.Umbraco.Analytics/1.0.0-beta004

Unfortunately I'm caught up in other projects, so most likely I won't be working on this anytime soon 😞
